### ISSUE TITLE
AvailableNumbers with enableTNDetail=true

### ISSUE THREAD

**Issue by philljones** [Bandwidth/csharp-bandwidth-iris#17]
If I call AvailableNumbers with enableTNDetail=false I get:

TelephoneNumberList = list of telephone numbers
TelephoneNumberDetailList = NULL

If I call AvailableNumbers with enableTNDetail=true I get:

TelephoneNumberList =NULL
TelephoneNumberDetailList = detailed list of of telephone numbers BUT BUT the actual TelephoneNumber field is NULL

**Comment by avbel** [comment]
Do you mean `TelephoneNumber` of  type `TelephoneNumberDetail` is null?

**Comment by philljones** [comment]
Correct. That's what I am seeing.

**Comment by avbel** [comment]
Found the reason of this issue. Use property `FullNumber` instead of `TelephoneNumber` of `TelephoneNumberDetail`. Fixed in `1.0.7`. Update it from nuget please.

**Comment by philljones** [comment]
@avbel working. Thanks for the quick fix and push to nuget.
