### ISSUE TITLE
[BUG] AllowAutoRedirect should be false

### ISSUE THREAD

**Issue by huytrieuCL** [Bandwidth/csharp-bandwidth-iris#75]
### Checklist
 - [x] Have you provided a description of the bug?
 - [x] Have you provided your Environment information?
 - [x] Have you provided a sample code snippet?
 - [x] Have you provided a stack trace?
 - [x] Have you outlined the expected behavior?

### Description
I'm calling InServiceNumber.List(client) without specifying any parameter. In this API, Bandwidth return Redirect 303, but with `AllowAutoRedirect = true`, Client will auto redirect to the Location header in the 303 response without adding `Authorization` header then it lead to 401 Unauthorized response.

`AllowAutoRedirect` should be set to `false`,  redirect response would already be handled in Client.MakeGetRequest()
`if (response.StatusCode == HttpStatusCode.RedirectMethod)`
 
### Environment Information

 - OS Version: _Mac M1_
 - SDK Version: _4.0.1_
 - Environment: _.NET 6_

### Sample Code Snippet

```csharp
private HttpClient CreateHttpClient()
    {
      UriBuilder uriBuilder = new UriBuilder(this._apiEndpoint)
      {
        Path = string.Format("/{0}/", (object) this._apiVersion)
      };
      HttpClient httpClient = new HttpClient((HttpMessageHandler) new HttpClientHandler()
      {
        AllowAutoRedirect = true,
      });
      httpClient.BaseAddress = uriBuilder.Uri;
      httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", Convert.ToBase64String(Encoding.UTF8.GetBytes(string.Format("{0}:{1}", (object) this._userName, (object) this._password))));
      httpClient.DefaultRequestHeaders.Add("User-Agent", Client.USER_AGENT);
      return httpClient;
    }
```

### Stack Trace
```shell
Bandwidth.Iris.BandwidthIrisException: Http code Unauthorized
   at Bandwidth.Iris.Client.MakeGetRequest(String path, IDictionary`2 query, String id, Boolean disposeResponse)
   at Bandwidth.Iris.Client.MakeGetRequest[TResult](String path, IDictionary`2 query, String id)
   at Bandwidth.Iris.Model.InServiceNumber.List(Client client, IDictionary`2 query)
```

### Expected Behavior
Add Authorization into redirect request

### Suggested Fix
Set AllowAutoRedirect = false like it was before https://github.com/Bandwidth/csharp-bandwidth-iris/pull/45/commits merged

**Comment by ajrice6713** [comment]
Hey @huytrieuCL - thanks for taking the time to open this issue, sorry it was missed! 

Let me get this corrected and released today in 6.0.1
