### ISSUE TITLE
[BUG] No OrderId is returned when using the Lidb class

### ISSUE THREAD

**Issue by yuri-viirtue** [Bandwidth/csharp-bandwidth-iris#78]
### Checklist
 - [x] Have you provided a description of the bug?
 - [x] Have you provided your Environment information?
 - [x] Have you provided a sample code snippet?
 - [x] Have you provided a stack trace?
 - [x] Have you outlined the expected behavior?

### Description
No OrderId property is returned when using the Lidb class. This was initially discovered using Lidb.Create() method, but the same behavior occurs with Lidb.Get();

![bandwidth-bug](https://github.com/Bandwidth/csharp-bandwidth-iris/assets/131686295/79ec6abf-f77a-4249-a212-6f6ba6dfa54d)

### Environment Information

 - OS Version: macOS Ventura 13.2.1
 - SDK Version: 6.0.0
 - Environment: .NET Core 6.0

### Sample Code Snippet
Any regular call to Lidb should reproduce the error:

```csharp
var result = await Lidb.Create(Client, new Lidb
{
    CustomerOrderId = "<any-customer-order-id>",
    LidbTnGroups = new LidbTnGroup[]
    {
        new()
        {
            TelephoneNumbers = new[]
            {
               "<any-tn>" 
            },
            SubscriberInformation = "<any-sub-info>",
            UseType = "RESIDENTIAL", 
            Visibility = "PUBLIC" 
        }
    }
});

```
or
```csharp
var result = await Lidb.Get(Client, "<order-id>");
```

### Stack Trace
This bug does not throw an error or exception.

### Expected Behavior
The API call from Postman returns the orderId correctly, as shown:

![Screenshot 2023-11-29 at 10 49 13 AM](https://github.com/Bandwidth/csharp-bandwidth-iris/assets/131686295/1f649721-6fd4-44bf-bc78-06963e71526a)

Lidb class should mirror this behavior.

### Suggested Fix
Going through the code, one can see that Lidb's orderId has a potential issue regarding case sensitivity. In the API result shown above, OrderId is returned in PascalCase, not camelCase. Removing the annotation might solve this.

![Screenshot 2023-11-29 at 10 56 01 AM](https://github.com/Bandwidth/csharp-bandwidth-iris/assets/131686295/0ef9bf90-41f8-4534-b1f0-b2df36eb1464)

**Comment by ajrice6713** [comment]
This is fixed in v6.0.1!
